object VersionConstants {
    val appName = "mega"
    val gdxVersion = "1.11.0"
    val gdxControllersVersion = "2.2.2"
    val roboVMVersion = "2.3.7"
    val box2DLightsVersion = "1.4"
    val ashleyVersion = "1.7.0"
    val aiVersion = "1.8.0"
    val libKtxVersion = "1.11.0-rc3"
    val visuiVersion = "1.4.2"
    val gson_version = "2.8.6"
    val reflections_version = "0.9.12"
    val gdxVideoVersion = "1.3.2-SNAPSHOT"
    val segmentVersion = "+"
}